### ISSUE TITLE
Configuração do Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by KilviaSantos** [KilviaSantos/agenda#1]
Instale e configure o JDK (Java Development Kit) no seu sistema operacional.
Instale um IDE (Integrated Development Environment) de sua preferência, como o Eclipse ou IntelliJ IDEA.
Baixe a biblioteca JDBC para SQLite a partir do link fornecido e adicione-a ao classpath do seu projeto.

Implementar a instalação automatizada dessas ferramentas através do Docker.

**Comment by AbraaoAlves** [comment]
DONE
